# Marine Intelligence Signal Normalization

This notebook demonstrates how AIS, weather, and hydrology datasets
are normalized into a unified schema.

**Import Libraries**

In [16]:
import pandas as pd

**Load CSV Files**

In [17]:
import pandas as pd

ais = pd.read_csv("../data/ais_standardized.csv")
weather = pd.read_csv("../data/weather_standardized.csv")
water = pd.read_csv("../data/water_standardized.csv")

print("AIS rows:", len(ais))
print("Weather rows:", len(weather))
print("Water rows:", len(water))

AIS rows: 7239758
Weather rows: 366
Water rows: 312

**Preview Dataset**

In [21]:
ais.head()

,source_id,timestamp,latitude,longitude,feature_type,normalized_value,source_reference
0,368084090,2022-01-01 00:00:00,29.93174,-89.99243,vessel_speed,6.0,AIS
1,368140160,2022-01-01 00:00:00,30.33475,-87.14429,vessel_speed,0.0,AIS
2,366941830,2022-01-01 00:00:02,29.30919,-94.79702,vessel_speed,0.0,AIS
3,316005971,2022-01-01 00:00:06,46.50268,-84.35674,vessel_speed,2.4,AIS
4,316004054,2022-01-01 00:00:07,46.50326,-84.37506,vessel_speed,0.3,AIS

In [22]:
weather.head()
water.head()

,source_id,timestamp,latitude,longitude,feature_type,normalized_value,source_reference
0,US1TXTV0053,2022-01-05,NaN,NaN,precipitation,0.0,NOAA
1,US1TXTV0053,2022-01-06,NaN,NaN,precipitation,0.0,NOAA
2,US1TXTV0053,2022-01-09,NaN,NaN,precipitation,0.0,NOAA
3,US1TXTV0053,2022-01-10,NaN,NaN,precipitation,0.0,NOAA
4,US1TXTV0053,2022-01-11,NaN,NaN,precipitation,0.0,NOAA

**Define Unified Schema**

In [23]:
columns = [
"source_id",
"timestamp",
"latitude",
"longitude",
"feature_type",
"normalized_value",
"source_reference"
]

**Normalize Datasets**

In [19]:
ais = ais[columns]
weather = weather[columns]
water = water[columns]

**Show Dataset Size**

In [24]:
signals.shape

(7240436, 7)

**Merge All Signals**

In [20]:
signals = pd.concat([ais, weather, water], ignore_index=True)

signals.head()

,source_id,timestamp,latitude,longitude,feature_type,normalized_value,source_reference
0,368084090,2022-01-01 00:00:00,29.93174,-89.99243,vessel_speed,6.0,AIS
1,368140160,2022-01-01 00:00:00,30.33475,-87.14429,vessel_speed,0.0,AIS
2,366941830,2022-01-01 00:00:02,29.30919,-94.79702,vessel_speed,0.0,AIS
3,316005971,2022-01-01 00:00:06,46.50268,-84.35674,vessel_speed,2.4,AIS
4,316004054,2022-01-01 00:00:07,46.50326,-84.37506,vessel_speed,0.3,AIS

## Conclusion

AIS vessel signals, weather signals, and hydrology signals were
successfully normalized into a unified schema.

This dataset will be ingested into the Marine Intelligence Signal
Database using the ingestion pipeline.